### PR TITLE
Add eviction channel

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Useful when caching file descriptors

### CODE REVIEW

**Comment by dgrijalva** [comment]
Cool idea.  Why not include the key in the callback?

**Comment by AudriusButkevicius** [comment]
Updated.

**Comment by dgrijalva** [comment]
Thanks.

One remaining concern: this callback is called while the lock is still held.  This means any access to the cache from the callback will result in a deadlock.  I'm assuming your usage is something like this:

``` go
myCache.EvictionCallback = func(key string, val interface{}){
    val.(*os.File).Close()
}
```

That is totally safe (assuming you're _sure_ about the type of `val`), but imagine this other, apparently benign callback:

``` go
myCache.EvictionCallback = func(key string, val interface{}){
    // Debug
    fmt.Printf("Evicted %v: Remaining entries %v", key, myCache.Len())
}
```

This will deadlock, since `Len` tries to grab the lock.

**Comment by dgrijalva** [comment]
My recommendation would be to make this a channel instead:

``` go
type Eviction struct {
    Key string
    Value interface{}
}

myCache.EvictionChan = make(chan Eviction, bufferSize)
```

You could also use goroutines internally, but this approach gives the most control to the user of the library.

**Comment by AudriusButkevicius** [comment]
But how do you clean up this routine that you've spawned for handling evictions?
Who closes the channel?

You'd then have to set a finalizer on the lfu...

**Comment by AudriusButkevicius** [comment]
See this version, but I have no way of testing closing the channel.

**Comment by dgrijalva** [comment]
Channels do not have to be closed.  The garbage collector will find them and clean them up just fine.

**Comment by dgrijalva** [comment]
This is a place where it's better to do less in the library.  There are lots of ways the developer might want to manage this.  For example, a dev have more than one cache that share an eviction channel.  The finalizer approach is clever, but i think it's over-solving the problem.

**Comment by dgrijalva** [comment]
Without the finalizer, i think this is ready to land.

**Comment by AudriusButkevicius** [comment]
Done.

**Comment by AudriusButkevicius** [comment]
So I still don't understand who'd eventually close the channel.

I think because a go routine will be waiting for data off the channel, I don't think it will ever get GCed, therefore I don't think this routine waiting for data will ever terminate, unless the user closes it from the outside.

For example I will do:

``` go
ch := make(chan lfu.Eviction)
c := lfu.New()
c.EvictionChannel = ch

go func() {
  for eviction := range ch {
      eviction.Value.(*os.File).Close()
  }
}()

c.Evict(c.Len())
close(ch)
```

But this feels wrong as the user is neither the reader nor the writer... It's just some external factor closing stuff.

**Comment by dgrijalva** [comment]
It's a great point.  There are several patterns for lifecycle management which are appropriate in different situations.  The cache object itself isn't really a good place to arbitrate the lifecycle of external things.  It's best to let users decide how they want to manage this, which is precisely what this implementation does.

Here are a few use cases (pardon sloppy code; i'm typing right into the comment form):

1) Long/forever lived cache.  This is actually a very common use case for a cache like this.  It may just live for the entire life of the process.  In this case, cleanup is never necessary.

2) Used as part of some other, lifecycle-managed task. 

``` go

type MyAwesomeTask struct {
    cache *lfu.Cache
    evictions chan lfu.Eviction
    closeChan chan int
}

func (t *MyAwesomeTak) Start() {
    t.evictions = make(chan lfu.Eviction)
    cache.EvictionChan = t.evictions
    go t.watchEvictions()
    go t.doAwesomeThings()
}

func (t *MyAwesomeTask) watchEvictions() {
   for {
      select {
          case e := <- t.evictions:
              /// do things
          case <- t.closeChan:
              return
      }
   }
}

func (t *MyAwesomeTask) doAwesomeThings() {
   t := time.Ticker(time.Second)
   for {
      select {
          case <- t.closeChan:
              go t.cleanupCache()
              return
          default: 
              // do an awesome thing
      }
   }
}

func (t *MyAwesomeTask) cleanupCache() {
   // there's probably a better way, but this should totally drain the cache
   // importantly - this flow allows this to happen after the main function of this
   // task has stopped happening
   t.cache.Evict(t.cache.Len())
   for {
      select {
          case e := <- t.evictions:
              // do cleanup stuff
          default: 
            // done
              return
      }
   }
}

func (t *MyAwesomeTask) Stop() {
    close(t.closeChan)
}
```

**Comment by dgrijalva** [comment]
I generally think of finalizers as code smell, but there's nothing preventing you from including that same finalizer in your implementation when you use this library.  If that's what works best for your use case, go for it.

**Comment by AudriusButkevicius** [comment]
I agree, makes perfect sense.

**Pull request merged**
